### ISSUE TITLE
Chore: change route

### ISSUE THREAD

**Issue by MrMyatNoe** [KaungHtetNaing24/laravel-sanctum-api#2]
1. post method (-/api/product-model) 
2. get method (-/api/product-model)
3. put method (-/api/product-model)
4. delete method (-/api/product-model/{id})

**return data that you want to add in post and put method
delete method return message**

https://davisonpro.medium.com/how-to-create-an-advanced-php-rest-api-c7afe6dd2694

https://mshossain.me/blog/designing-laravel-rest-api-best-practices/

**Comment by KaungHtetNaing24** [comment]
fixed: change route names in api and return datas
